codecov:
  token: 39d98653-9a46-4e9d-af9b-c1ed77d19736
  branch: master
  bot: null

coverage:
  precision: 2
  round: down
  range: "70...100"

  notify:
    slack:
      _custom_:
        url: null
        threshold: null
        branches: null
        attachments: "sunburst, diff"

    hipchat:
      _custom_:
        url: null
        notify: no
        threshold: null
        branches: null
        card: yes
        only_pulls: null
        message: null

    gitter:
      _custom_:
        url: null
        threshold: null
        branches: null
        message: null

    webhook:
      _custom_:
        url: null
        threshold: null
        branches: null
        only_pulls: null

    irc:
      _custom_:
        server: null
        branches: null
        threshold: null
        message: null

  status:
    project:
      default:
        target: auto
        threshold: null
        branches: null

    patch:
      default:
        target: auto
        branches: null

    changes:
      default:
        branches: null

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches: null
  behavior: default